# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: 183631301567.dkr.ecr.eu-west-1.amazonaws.com/lamp-app:latest
        # image: nginx:latest
        
        ports:
        - containerPort: 80
        env:
          - name: DB_CONNECTION
            valueFrom:
              configMapKeyRef:
                name: laravel-config
                key: DB_CONNECTION
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: laravel-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: laravel-config
                key: DB_PORT
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: laravel-config
                key: DB_DATABASE
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: laravel-config
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: laravel-config
                key: DB_PASSWORD
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
