apiVersion: v1                          # Core API version.
kind: Service                           # Declares a Kubernetes Service.
metadata:
  name: laravel-service                 # Name of the service.
spec:

  selector:
    app: laravel                        # Targets pods with label app=laravel.
  ports:
  - protocol: TCP
    port: 80                            # Service port exposed to other services or ingress.
    targetPort: 80                      # Port inside the container.
  type: LoadBalancer  # ← Correct type for Terraform ALB integration                  # Default service type; internal-only service within the cluster.
