# Global configuration for Prometheus
global:
  # How often to scrape targets by default
  scrape_interval: 15s

scrape_configs:
  # Configuration for scraping Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus server endpoint

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    
  
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['fastapi-app:8000']
    metrics_path: '/metrics'
